"""add chat_histories_odonto table.

Revision ID: 352d5a24eefc
Revises: b25d38b0cd7c
Create Date: 2026-05-12 07:53:54.148824

"""
from typing import Sequence, Union

import sqlmodel  # noqa: F401
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '352d5a24eefc'
down_revision: Union[str, Sequence[str], None] = 'b25d38b0cd7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_histories_odonto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_histories_odonto_session_id'), 'chat_histories_odonto', ['session_id'], unique=False)
    op.create_table('thread',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thread')
    op.drop_index(op.f('ix_chat_histories_odonto_session_id'), table_name='chat_histories_odonto')
    op.drop_table('chat_histories_odonto')
    # ### end Alembic commands ###
